# docker-compose -f docker-compose-environment.yml up -d
version: '3'
services:
  ollama:
    image: ollama/ollama:0.5.10
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - my-network
    volumes:
      - ${ROOT_PATH}/ollama/data:/root/.ollama

networks:
  my-network:
    driver: bridge