# 命令执行 docker-compose up -d
version: '3.9'
services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    restart: always
    user: "root"  # 使用root用户运行容器，解决权限问题
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=labelstudio
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=postgres
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=label-studio-db
      - LABEL_STUDIO_HOST=http://localhost:11000
      - LABEL_STUDIO_BASE_DATA_DIR=/label-studio/data
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data/media
    ports:
      - "11000:8080"
    volumes:
      - ${ROOT_PATH}/label-studio/data:/label-studio/data  # 数据目录
    depends_on:
      label-studio-db:
        condition: service_healthy  # 确保数据库完全启动后再启动label-studio
    networks:
      - my-network

  label-studio-db:
    image: postgres:13
    container_name: label-studio-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=labelstudio
    volumes:
      - ${ROOT_PATH}/label-studio/postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  my-network:
    driver: bridge