version: '3'

services:
  frps:
    image: snowdreamtech/frps:0.51.3
    container_name: frps
    restart: always
    network_mode: host
    volumes:
      - ${ROOT_PATH}/frp-server/frps.ini:/etc/frp/frps.ini