version: '3.9'

services:
  qualitis-server:
    build:
      context: D:\volume\qualitis  # 指向源码根目录
      dockerfile: Dockerfile.backend  # 后端编译构建脚本
    container_name: qualitis-server
    restart: always  # 添加重启策略
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_MASTER_URL=jdbc:mysql://127.0.0.1:3306/qualitis?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_MASTER_USERNAME=root
      - SPRING_DATASOURCE_MASTER_PASSWORD=123456
      - SERVER_PORT=8090
    ports:
      - "8090:8090"
    volumes:
      - ${ROOT_PATH}/qualitis/logs:/opt/qualitis/logs  # 使用ROOT_PATH环境变量
    networks:
      - my-network  # 使用统一网络

  qualitis-ui:
    build:
      context: D:\volume\qualitis/ui  # 前端源码目录
      dockerfile: Dockerfile.frontend  # 前端编译构建脚本
    container_name: qualitis-ui
    restart: always  # 添加重启策略
    depends_on:
      - qualitis-server
    ports:
      - "80:80"  # 修改端口避免冲突
    volumes:
      - ${ROOT_PATH}/qualitis/ui:/opt/qualitis-ui  # 使用ROOT_PATH环境变量
    networks:
      - my-network  # 使用统一网络

networks:
  my-network:  # 使用统一网络名称
    driver: bridge