# 命令执行 docker-compose up -d
version: '3.9'
services:
  minio1:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    volumes:
      - ./minio/m1_data:/data
    networks:
      - my-network
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server http://minio{1...3}/data --console-address ":9001"

  minio2:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    volumes:
      - ./minio/m2_data:/data
    networks:
      - my-network
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server http://minio{1...3}/data --console-address ":9001"

  minio3:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    volumes:
      - ./minio/m3_data:/data
    networks:
      - my-network
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server http://minio{1...3}/data --console-address ":9001"

networks:
  my-network:
    driver: bridge