# 命令执行 docker-compose up -d
version: '3.9'
services:
  nacos:
    image: nacos/nacos-server:v2.0.3
    # 强制使用 amd64 架构
    platform: linux/amd64  
    container_name: nacos
    restart: always
    ports:
      # HTTP API 端口
      - "18848:8848" 
      # gRPC 端口
      - "19848:9848"
    environment:
      # 运行模式：standalone 单机模式
      - MODE=standalone
      # 基础配置
      - PREFER_HOST_MODE=hostname
      # 使用 MySQL 作为数据源
      - SPRING_DATASOURCE_PLATFORM=mysql
      # MySQL 主机地址
      - MYSQL_SERVICE_HOST=mysql
      # 数据库名称
      - MYSQL_SERVICE_DB_NAME=nacos_config
      # MySQL 端口（容器内部端口）
      - MYSQL_SERVICE_PORT=3306
      # MySQL 用户名
      - MYSQL_SERVICE_USER=root
      # MySQL 密码
      - MYSQL_SERVICE_PASSWORD=123456
      # MySQL 连接参数 (修复字符集为 utf8mb4)
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8mb4&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        # JVM 内存配置
      - JVM_XMS=512m
      - JVM_XMN=256m
      - JVM_XMX=1024m
      # 关闭鉴权（开发环境）
      - NACOS_AUTH_ENABLE=false
    networks:
      - my-network
    volumes:
      - ${ROOT_PATH}/nacos/logs:/home/nacos/logs  # 挂载日志目录
      - ${ROOT_PATH}/nacos/data:/home/nacos/data  # 挂载数据目录
    depends_on:
      - mysql

networks:
  my-network:
    name: my-network
    driver: bridge
