version: '3'

services:
  frps:
    image: snowdreamtech/frps:latest
    container_name: frps
    restart: always
    network_mode: host
    volumes:
      - ${ROOT_PATH}/frp/server/frps.ini:/etc/frp/frps.ini
    ports:
      - "7000:7000"   # FRP服务端口
      - "7500:7500"   # FRP控制面板端口
      - "9100-9200:9100-9200"  # 映射端口范围，可根据需要调整 