version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
    container_name: minio
    restart: always
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_LANGUAGE=zh-CN
      # 性能优化
      - MINIO_CACHE=on
      - MINIO_CACHE_DRIVES=/data/.cache
      - MINIO_CACHE_EXCLUDE=*.pdf,*.mp4
      - MINIO_CACHE_QUOTA=80
      - MINIO_CACHE_AFTER=3
      - MINIO_CACHE_WATERMARK_LOW=70
      - MINIO_CACHE_WATERMARK_HIGH=90
      # 压缩选项
      - MINIO_COMPRESS=true
      - MINIO_COMPRESS_EXTENSIONS=.txt,.log,.csv,.json,.md,.html
      - MINIO_COMPRESS_MIME_TYPES=text/*,application/json,application/xml
    volumes:
      - ${ROOT_PATH}/minio/data:/data
    ports:
      - '9110:9000'
      - '9111:9001'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - my-network

networks:
  my-network:
    driver: bridge 