version: '3'
services:
  open-webui:
    image: open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
      - USERID=1000
    volumes:
      - ${ROOT_PATH}/open-webui/data/webui:/app/backend/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge